model: ContrastiveEmbeddingModel
run_config :
  verbose : 2
  debug : True
  num_threads : 64

model_config :
  name : ContrastiveModel
  projection_dim : 8
  projection_blocks : 3
  backbone_layers : [32,16]
  latent_dim : 4
  encoder_layers : [8,6]
  decoder_layers : [6,8]

training_config :
  constrastive_epochs : 50
  epochs : 30
  batch_size : 256
  learning_rate : 0.00001
  validation_split : 0.1

  EarlyStopping_patience : 10

  ReduceLROnPlateau_factor : 0.5
  ReduceLROnPlateau_patience : 5
  ReduceLROnPlateau_min_lr : 0.00001

  embedding_loss : 'SimCLR'